//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms
{


    public partial class IncidentReport
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertIcon;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.TextBox txtOccurTime;
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
