//------------------------------------------------------------------------------
// <auto-generated>
//     这段代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms {
    public partial class NewsDetail {
        /// <summary>
        /// lblMessage 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblTitle 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTitle;

        /// <summary>
        /// lblMeta 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMeta;

        /// <summary>
        /// litContent 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litContent;

        /// <summary>
        /// lnkBack 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
    }
}