//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms {

    public partial class NewsPublished {

        /// <summary>
        /// lblMessage 控件。
        /// 小白讲解：用于显示提示信息，例如“已下架该新闻”。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// gvNews 控件。
        /// 小白讲解：展示已发布新闻列表，并支持“下架”按钮。
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvNews;
    }
}

