//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms
{


    public partial class UserManage
    {
        /// <summary>
        /// lblMessage 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// gvUsers 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
